### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by ghost** [Pawsative/Applejack#6]
Anywhere i can get a .sql file?

**Comment by Pawsative** [comment]
It automatically creates the SQL file @ https://github.com/Pawsative/Applejack/blob/master/gamemode/init.lua#L111, if you want them they're right there.

**Comment by ghost** [comment]
[ERROR] gamemodes/applejack/gamemode/external/sv_mysqlite.lua:262: attempt to index global 'databaseObject' (a nil value)
  1. query - gamemodes/applejack/gamemode/external/sv_mysqlite.lua:262
   2. Query - gamemodes/applejack/gamemode/init.lua:141
    3. get - gamemodes/applejack/gamemode/libraries/sv_inventory.lua:15
     4. v - gamemodes/applejack/gamemode/libraries/sv_inventory.lua:37
      5. unknown - lua/includes/modules/hook.lua:84

> >:(

**Comment by ghost** [comment]
![Screenshot (6351)](https://user-images.githubusercontent.com/58396738/85905064-4a0c8000-b802-11ea-99e9-9d85b876f8ab.png)
